version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
